// src/app/login.tsx
import { LinearGradient } from 'expo-linear-gradient';
import { Image } from 'expo-image';
import { router } from 'expo-router';
import { StatusBar } from 'expo-status-bar';
import { useState, type ReactNode } from 'react';
import {
  ActivityIndicator,
  Alert,
  Animated,
  KeyboardAvoidingView,
  Platform,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  View,
  type LayoutChangeEvent,
} from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

import { useAuth } from '@/stores/auth';

type Mode = 'login' | 'register';
type Field = 'username' | 'email' | 'password';

const LOGIN_BG = require('../../assets/images/login-bg.png');
const LOGO = require('../../assets/images/logo.png');

/** 品牌主色（与小程序工程 apps/miniprogram 一致） */
const BRAND = '#FF6B3D';
const GRADIENT: readonly [string, string, ...string[]] = ['#FF6B3D', '#FF8F5E'];

export default function LoginScreen() {
  const { signIn, signUp } = useAuth();
  const insets = useSafeAreaInsets();

  const [mode, setMode] = useState<Mode>('login');
  const [username, setUsername] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [focused, setFocused] = useState<Field | null>(null);
  const [loading, setLoading] = useState(false);
  const [rowWidth, setRowWidth] = useState(0);
  // 以 state 持有稳定的动画值对象（避免编译器 refs 规则）
  const [slider] = useState(() => new Animated.Value(0));
  // 滑块宽度 = (容器宽 - 两侧 padding 6) / 2，滑动位移与其自身宽度一致
  const slotWidth = (rowWidth - 6) / 2;

  const switchMode = (next: Mode) => {
    if (next === mode) return;
    setMode(next);
    Animated.timing(slider, {
      toValue: next === 'register' ? slotWidth : 0,
      duration: 260,
      useNativeDriver: true,
    }).start();
  };

  const onTabRowLayout = (e: LayoutChangeEvent) => {
    const { width } = e.nativeEvent.layout;
    if (width !== rowWidth) setRowWidth(width);
  };

  const handleSubmit = async () => {
    if (!username.trim()) {
      Alert.alert('提示', '请输入用户名');
      return;
    }
    if (mode === 'register' && !email.trim()) {
      Alert.alert('提示', '请输入邮箱');
      return;
    }
    if (!password || password.length < 6) {
      Alert.alert('提示', '密码至少 6 位');
      return;
    }

    setLoading(true);
    try {
      if (mode === 'login') {
        await signIn(username.trim(), password);
      } else {
        await signUp({
          username: username.trim(),
          email: email.trim(),
          password,
        });
      }
      router.replace('/');
    } catch (error) {
      const message =
        error instanceof Error ? error.message : '操作失败，请稍后重试';
      Alert.alert(mode === 'login' ? '登录失败' : '注册失败', message);
    } finally {
      setLoading(false);
    }
  };

  const isLogin = mode === 'login';

  return (
    <View style={styles.root}>
      <StatusBar style="light" />
      <Image
        source={LOGIN_BG}
        style={StyleSheet.absoluteFill}
        contentFit="cover"
        transition={200}
      />
      <LinearGradient
        colors={[
          'rgba(0,0,0,0.35)',
          'rgba(0,0,0,0.08)',
          'rgba(0,0,0,0.15)',
          'rgba(0,0,0,0.55)',
        ]}
        locations={[0, 0.35, 0.65, 1]}
        style={StyleSheet.absoluteFill}
      />

      <KeyboardAvoidingView
        style={styles.flex}
        behavior={Platform.OS === 'ios' ? 'padding' : undefined}
      >
        <ScrollView
          contentContainerStyle={[
            styles.content,
            { paddingTop: insets.top + 16, paddingBottom: insets.bottom + 20 },
          ]}
          keyboardShouldPersistTaps="handled"
          showsVerticalScrollIndicator={false}
        >
          {/* 品牌区 */}
          <View style={styles.brandArea}>
            <View style={styles.logoBackdrop}>
              <Image source={LOGO} style={styles.logo} contentFit="contain" />
            </View>
            <Text style={styles.brandName}>途旅 AI</Text>
            <Text style={styles.brandDesc}>探索世界，从一次对话开始</Text>
          </View>

          {/* 表单卡片（玻璃拟态） */}
          <View style={styles.formCard}>
            {/* 登录 / 注册 切换 */}
            <View style={styles.tabRow} onLayout={onTabRowLayout}>
              {rowWidth > 0 && (
                <Animated.View
                  style={[
                    styles.tabSlider,
                    { width: slotWidth, transform: [{ translateX: slider }] },
                  ]}
                />
              )}
              {(['login', 'register'] as const).map((item) => {
                const active = mode === item;
                return (
                  <Pressable
                    key={item}
                    style={styles.tabItem}
                    onPress={() => switchMode(item)}
                  >
                    <Text style={[styles.tabText, active && styles.tabTextActive]}>
                      {item === 'login' ? '登录' : '注册'}
                    </Text>
                  </Pressable>
                );
              })}
            </View>

            {/* 用户名 */}
            <InputGroup label="用户名" focused={focused === 'username'}>
              <TextInput
                style={inputFieldStyle(focused === 'username')}
                placeholder="请输入用户名"
                placeholderTextColor="#bbb"
                value={username}
                onChangeText={setUsername}
                onFocus={() => setFocused('username')}
                onBlur={() => setFocused((v) => (v === 'username' ? null : v))}
                autoCapitalize="none"
                autoCorrect={false}
                returnKeyType="next"
              />
            </InputGroup>

            {/* 邮箱（仅注册） */}
            {mode === 'register' && (
              <InputGroup label="邮箱" focused={focused === 'email'}>
                <TextInput
                  style={inputFieldStyle(focused === 'email')}
                  placeholder="请输入邮箱"
                  placeholderTextColor="#bbb"
                  value={email}
                  onChangeText={setEmail}
                  onFocus={() => setFocused('email')}
                  onBlur={() => setFocused((v) => (v === 'email' ? null : v))}
                  keyboardType="email-address"
                  autoCapitalize="none"
                  autoCorrect={false}
                  returnKeyType="next"
                />
              </InputGroup>
            )}

            {/* 密码 */}
            <InputGroup label="密码" focused={focused === 'password'}>
              <TextInput
                style={inputFieldStyle(focused === 'password')}
                placeholder="请输入密码"
                placeholderTextColor="#bbb"
                value={password}
                onChangeText={setPassword}
                onFocus={() => setFocused('password')}
                onBlur={() => setFocused((v) => (v === 'password' ? null : v))}
                secureTextEntry
                returnKeyType="done"
                onSubmitEditing={handleSubmit}
              />
            </InputGroup>

            {/* 提交 */}
            <LinearGradient
              colors={GRADIENT}
              start={{ x: 0, y: 0 }}
              end={{ x: 1, y: 1 }}
              style={[styles.submit, loading && styles.submitDisabled]}
            >
              <Pressable
                style={styles.submitInner}
                onPress={handleSubmit}
                disabled={loading}
              >
                {loading ? (
                  <ActivityIndicator color="#ffffff" />
                ) : (
                  <Text style={styles.submitText}>
                    {isLogin ? '登 录' : '注 册'}
                  </Text>
                )}
              </Pressable>
            </LinearGradient>
          </View>

          {/* 弹性占位：大屏时将提示行推向页脚 */}
          <View style={styles.spacer} />

          {/* 底部切换提示 */}
          <Text style={styles.footerTip}>
            {isLogin ? '还没有账号？' : '已有账号？'}
            <Text
              style={styles.footerLink}
              onPress={() => switchMode(isLogin ? 'register' : 'login')}
            >
              {isLogin ? '立即注册' : '去登录'}
            </Text>
          </Text>
        </ScrollView>
      </KeyboardAvoidingView>
    </View>
  );
}

function InputGroup({
  label,
  focused,
  children,
}: {
  label: string;
  focused: boolean;
  children: ReactNode;
}) {
  return (
    <View style={[styles.inputGroup, focused && styles.inputGroupFocused]}>
      <Text style={styles.inputLabel}>{label}</Text>
      {children}
    </View>
  );
}

function inputFieldStyle(focused: boolean) {
  return [
    styles.inputField,
    focused && {
      borderColor: BRAND,
      backgroundColor: '#FFF8F5',
    },
  ];
}

const styles = StyleSheet.create({
  flex: { flex: 1 },
  root: { flex: 1, backgroundColor: '#111418' },

  /* ======== 品牌区 ======== */
  content: {
    flexGrow: 1,
    paddingHorizontal: 36,
  },
  spacer: { flex: 1, minHeight: 16 },
  brandArea: { alignItems: 'center', marginBottom: 30 },
  logoBackdrop: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: 'rgba(255,255,255,0.96)',
    shadowColor: '#000',
    shadowOpacity: 0.14,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  logo: { width: 42, height: 42 },
  brandName: {
    fontSize: 22,
    fontWeight: '700',
    color: '#ffffff',
    letterSpacing: 4,
    textShadowColor: 'rgba(0,0,0,0.25)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 8,
  },
  brandDesc: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.88)',
    marginTop: 7,
    letterSpacing: 1.5,
    textShadowColor: 'rgba(0,0,0,0.2)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 6,
  },

  /* ======== 表单卡片（玻璃拟态） ======== */
  formCard: {
    backgroundColor: 'rgba(255,255,255,0.96)',
    borderRadius: 14,
    padding: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.6)',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },

  /* ======== 标签切换 ======== */
  tabRow: {
    flexDirection: 'row',
    position: 'relative',
    marginBottom: 18,
    backgroundColor: '#F5F6FA',
    borderRadius: 10,
    padding: 3,
  },
  tabSlider: {
    position: 'absolute',
    top: 3,
    bottom: 3,
    left: 3,
    backgroundColor: '#ffffff',
    borderRadius: 8,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  tabItem: { flex: 1, alignItems: 'center', paddingVertical: 9 },
  tabText: { fontSize: 14, color: '#999' },
  tabTextActive: { color: BRAND, fontWeight: '600' },

  /* ======== 输入组 ======== */
  inputGroup: {
    marginBottom: 14,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'transparent',
    borderRadius: 10,
  },
  inputGroupFocused: { borderColor: 'transparent' },
  inputLabel: {
    fontSize: 12,
    color: '#666',
    marginBottom: 5,
    fontWeight: '500',
  },
  inputField: {
    height: 42,
    backgroundColor: '#F8F9FB',
    borderRadius: 10,
    paddingHorizontal: 14,
    fontSize: 15,
    color: '#1A1A1A',
    borderWidth: 1,
    borderColor: 'transparent',
  },

  /* ======== 提交按钮 ======== */
  submit: {
    marginTop: 16,
    borderRadius: 23,
    height: 46,
    shadowColor: BRAND,
    shadowOpacity: 0.35,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 5,
    overflow: 'hidden',
  },
  submitInner: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  submitDisabled: { opacity: 0.75 },
  submitText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
    letterSpacing: 2,
  },

  /* ======== 底部提示 ======== */
  footerTip: {
    marginTop: 20,
    fontSize: 13,
    color: 'rgba(255,255,255,0.85)',
    textAlign: 'center',
  },
  footerLink: {
    color: '#ffffff',
    fontWeight: '600',
    textDecorationLine: 'underline',
    marginLeft: 2,
  },
});

// apps/miniprogram/src/pages/login/index.vue
<template>
  <view class="login-page">
    <!-- Hero 背景图 -->
    <image class="hero-bg" src="/static/hero/login-bg.png" mode="aspectFill" />
    <view class="hero-overlay" />

    <!-- 主体内容 -->
    <view class="login-content" :style="{ paddingTop: (statusBarHeight + 30) + 'px' }">
      <!-- 品牌区 -->
      <view class="brand-area">
        <view class="logo-backdrop">
          <image class="brand-logo" src="/static/hero/logo.png" mode="aspectFit" />
        </view>
        <text class="brand-name">途旅 AI</text>
        <text class="brand-desc">探索世界，从一次对话开始</text>
      </view>

      <!-- 表单卡片（玻璃拟态） -->
      <view class="form-card">
        <!-- 切换标签 -->
        <view class="tab-row">
          <view
            class="tab-item"
            :class="{ active: mode === 'login' }"
            @click="mode = 'login'"
          >
            <text>登录</text>
          </view>
          <view
            class="tab-item"
            :class="{ active: mode === 'register' }"
            @click="mode = 'register'"
          >
            <text>注册</text>
          </view>
          <view class="tab-slider" :class="{ right: mode === 'register' }" />
        </view>

        <!-- 用户名 -->
        <view class="input-group">
          <text class="input-label">用户名</text>
          <input
            class="input-field"
            v-model="form.username"
            placeholder="请输入用户名"
            placeholder-style="color:#bbb"
          />
        </view>

        <!-- 邮箱（仅注册） -->
        <view class="input-group" v-if="mode === 'register'">
          <text class="input-label">邮箱</text>
          <input
            class="input-field"
            v-model="form.email"
            placeholder="请输入邮箱"
            placeholder-style="color:#bbb"
          />
        </view>

        <!-- 密码 -->
        <view class="input-group">
          <text class="input-label">密码</text>
          <input
            class="input-field"
            v-model="form.password"
            password
            placeholder="请输入密码"
            placeholder-style="color:#bbb"
          />
        </view>

        <!-- 提交 -->
        <button class="submit-btn" :loading="loading" @click="handleSubmit">
          {{ mode === 'login' ? '登 录' : '注 册' }}
        </button>
      </view>

      <!-- 底部切换提示 -->
      <view class="footer-tip" v-if="mode === 'login'">
        还没有账号？<text class="link" @click="mode = 'register'">立即注册</text>
      </view>
      <view class="footer-tip" v-else>
        已有账号？<text class="link" @click="mode = 'login'">去登录</text>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { reactive, ref } from 'vue'
import { loginApi, registerApi } from '@/api'

const mode = ref<'login' | 'register'>('login')
const loading = ref(false)

const { statusBarHeight = 20 } = uni.getSystemInfoSync()

const form = reactive({
  username: '',
  email: '',
  password: '',
})

async function handleSubmit() {
  if (!form.username.trim()) {
    uni.showToast({ title: '请输入用户名', icon: 'none' })
    return
  }
  if (mode.value === 'register' && !form.email.trim()) {
    uni.showToast({ title: '请输入邮箱', icon: 'none' })
    return
  }
  if (!form.password.trim() || form.password.length < 6) {
    uni.showToast({ title: '密码至少6位', icon: 'none' })
    return
  }

  loading.value = true
  try {
    if (mode.value === 'login') {
      await loginApi({ username: form.username, password: form.password })
    } else {
      await registerApi({
        username: form.username,
        email: form.email,
        password: form.password,
      })
    }
    uni.showToast({ title: mode.value === 'login' ? '登录成功' : '注册成功', icon: 'success' })
    uni.switchTab({ url: '/pages/chat/index' })
  } catch (err: any) {
    uni.showToast({ title: err?.data?.message || '操作失败', icon: 'none' })
  } finally {
    loading.value = false
  }
}
</script>

<style scoped>
.login-page {
  position: relative;
  width: 100vw;
  height: 100vh;
  overflow: hidden;
}

/* ======== Hero 背景 ======== */
.hero-bg {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: 1;
}

.hero-overlay {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background: linear-gradient(
    180deg,
    rgba(0, 0, 0, 0.35) 0%,
    rgba(0, 0, 0, 0.08) 35%,
    rgba(0, 0, 0, 0.15) 65%,
    rgba(0, 0, 0, 0.55) 100%
  );
  z-index: 2;
}

/* ======== 内容区 ======== */
.login-content {
  position: relative;
  z-index: 3;
  display: flex;
  flex-direction: column;
  align-items: center;
  height: 100%;
  padding: 0 72rpx;
  box-sizing: border-box;
}

/* ======== 品牌区 ======== */
.brand-area {
  display: flex;
  flex-direction: column;
  align-items: center;
  margin-top: 100rpx;
}

.logo-backdrop {
  width: 100rpx;
  height: 100rpx;
  border-radius: 50%;
  background: rgba(255, 255, 255, 0.94);
  box-shadow: 0 6rpx 24rpx rgba(0, 0, 0, 0.12);
  display: flex;
  align-items: center;
  justify-content: center;
  margin-bottom: 16rpx;
}

.brand-logo {
  width: 64rpx;
  height: 64rpx;
}

.brand-name {
  font-size: 36rpx;
  font-weight: 700;
  color: #fff;
  letter-spacing: 6rpx;
  text-shadow: 0 2rpx 12rpx rgba(0, 0, 0, 0.2);
}

.brand-desc {
  font-size: 22rpx;
  color: rgba(255, 255, 255, 0.85);
  margin-top: 8rpx;
  letter-spacing: 2rpx;
}

/* ======== 表单卡片（玻璃拟态） ======== */
.form-card {
  width: 100%;
  margin-top: 32rpx;
  background: rgba(255, 255, 255, 0.94);
  border-radius: 20rpx;
  padding: 28rpx 30rpx;
  box-shadow: 0 8rpx 36rpx rgba(0, 0, 0, 0.10);
  border: 1rpx solid rgba(255, 255, 255, 0.6);
}

/* ======== 标签切换 ======== */
.tab-row {
  display: flex;
  position: relative;
  margin-bottom: 24rpx;
  background: #F5F6FA;
  border-radius: 10rpx;
  padding: 4rpx;
}

.tab-item {
  flex: 1;
  text-align: center;
  padding: 10rpx 0;
  font-size: 26rpx;
  color: #999;
  border-radius: 8rpx;
  z-index: 1;
  transition: color 0.25s;
  position: relative;
}

.tab-item.active {
  color: #FF6B3D;
  font-weight: 600;
}

.tab-slider {
  position: absolute;
  top: 4rpx;
  left: 4rpx;
  width: calc(50% - 4rpx);
  height: calc(100% - 8rpx);
  background: #fff;
  border-radius: 8rpx;
  box-shadow: 0 2rpx 8rpx rgba(0, 0, 0, 0.06);
  transition: transform 0.3s cubic-bezier(0.4, 0, 0.2, 1);
}

.tab-slider.right {
  transform: translateX(100%);
}

/* ======== 输入组 ======== */
.input-group {
  margin-bottom: 16rpx;
}

.input-label {
  display: block;
  font-size: 22rpx;
  color: #666;
  margin-bottom: 6rpx;
  font-weight: 500;
}

.input-field {
  width: 100%;
  height: 72rpx;
  background: #F8F9FB;
  border-radius: 12rpx;
  padding: 0 20rpx;
  font-size: 24rpx;
  color: #1A1A1A;
  box-sizing: border-box;
  border: 2rpx solid transparent;
  transition: border-color 0.2s, background 0.2s;
}

.input-field:focus {
  border-color: #FF6B3D;
  background: #FFF8F5;
}

/* ======== 提交按钮 ======== */
.submit-btn {
  width: 100%;
  height: 72rpx;
  margin-top: 20rpx;
  background: linear-gradient(135deg, #FF6B3D 0%, #FF8F5E 100%);
  color: #fff;
  font-size: 28rpx;
  font-weight: 600;
  border-radius: 36rpx;
  border: none;
  display: flex;
  align-items: center;
  justify-content: center;
  letter-spacing: 4rpx;
  box-shadow: 0 4rpx 20rpx rgba(255, 107, 61, 0.35);
}

.submit-btn::after {
  border: none;
}

.submit-btn:active {
  opacity: 0.9;
  transform: scale(0.98);
}

/* ======== 底部提示 ======== */
.footer-tip {
  margin-top: 24rpx;
  font-size: 22rpx;
  color: rgba(255, 255, 255, 0.75);
}

.link {
  color: #fff;
  font-weight: 600;
  text-decoration: underline;
  text-underline-offset: 4rpx;
}
</style>
